### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by nitay** [ActionIQ/actioniq.github.io#6]

**Comment by sepans** [comment]
A ruby library is set up [here](https://github.com/ActionIQ/actioniq.github.io/blob/master/_config.yml#L72) to do that, which works perfect locally and minifies the code as Jekyll builds the pages. But since github.io runs Jekyll in safe mode it doesn't do anything. 

Solutions:

* host the website somewhere other than github.io that doesn't have that restriction
* Add minified version of index.html, css and js files to the repo and use them as Jekyll templated (not a good solution because it makes later tweaking of website hard and confusing)
* add _site directory to repo and disable set config file so it uses that directory instead of building it when it is deployed on github.io (This works fine but it is a non-standard way of using Jekyll that may make it confusing for someone who modifies the code but doesn't commit the generated code in _site directory to github)
* setup a grunt task (combining Jekyll and grunt for a static website is a little bit too much)

After all the performance gain by minifying html and css is neglectable. The js libraries which could affect page loading time are already minified. 
Uglifing just makes the source code not readable.

**Comment by nitay** [comment]
Gotcha, okay sounds like we can wait with this for now then. As you said it's not like our site is particularly big. Thanks for investigating.
